environment:
  nodejs_version: "18"

branches:
  only:
    - master
    - main

cache: 
  node_modules

install:
  - git config --global credential.helper "store --file=.git/credentials"
  - echo "https://lanoriya:${GH_TOKEN}@github.com" > .git/credentials
  - npm install

build: off

deploy_script:
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GH_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose
